name: yoonu_njub
description: Yoonu Njub

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.2.2+24

# 24 only Android - updating to Android 15/API 35
# 22 only for Android right now - getting internal testing track to sdk 33
# 21: android, ios, web - 20 corrects Android 12 launcher problem
# 19: macos

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  intl: any
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.2.1
  firebase_core: ^4.1.0
  firebase_analytics: ^12.0.1
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  path_provider: ^2.0.8
  scrollable_positioned_list: ^0.3.8
  http: ^1.0.0
  mailer: ^6.0.1
  flutter_html: ^3.0.0-alpha.6
  just_audio_background: ^0.0.1-beta.17
  package_info_plus: ^8.3.1
  share_plus: ^11.1.0
  connectivity_plus: ^6.0.1
  flutter_animate: ^4.2.0+1
  cupertino_icons: ^1.0.5
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  macos: true
  image_path: "dev_assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "dev_assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/html/
    - assets/icons/

  fonts:
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
    - family: Charis
      fonts:
        - asset: assets/fonts/CharisSILCompact-R.ttf
